#!/bin/bash

# Initialize a project to use designlens
# Creates /specs folder, lockfile, and AGENTS.md pointer

spec_init() {
  # Source helpers
  local lib_dir
  lib_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
  source "$lib_dir/colors.sh"
  source "$lib_dir/config.sh"
  source "$lib_dir/logo.sh"

  show_logo

  if ! command -v jq &>/dev/null; then
    error "jq is required but not installed. See https://jqlang.org/download/"
    exit 1
  fi

  if [ ! -d .git ]; then
    echo "Initializing git repository..."
    git init
    success "Git repository initialized"
  fi

  if [ -f .designlens.json ]; then
    error "Project is already initialized (.designlens.json exists). 'designlens init' is a one-shot command."
    exit 1
  fi

  if [ -d specs ]; then
    error "/specs folder already exists. Project is already initialized."
    exit 1
  fi

  echo "Initializing designlens project..."

  # Create /specs directory
  mkdir -p specs
  success "Created /specs directory"

  # Read metadata from installed tool
  METADATA_FILE="$lib_dir/../designlens.json"
  if [ -f "$METADATA_FILE" ]; then
    TOOL_VERSION=$(grep -o '"Version": *"[^"]*"' "$METADATA_FILE" | cut -d'"' -f4)
    TOOL_URL=$(grep -o '"URL": *"[^"]*"' "$METADATA_FILE" | cut -d'"' -f4)
  else
    TOOL_VERSION="unknown"
    TOOL_URL="https://github.com/ropensci/designlens"
  fi

  # Create project config file (metadata + local settings)
  cat > .designlens.json << EOF
{
  "tool": "designlens",
  "version": "$TOOL_VERSION",
  "docs": "$TOOL_URL/blob/main/docs/conventions.md",
  "active": true
}
EOF
  success "Created .designlens.json"

  echo ""
  rule
  echo ""

  # Ask about auto-commit preference (only on first init for this project)
  echo ""
  prompt "Would you like completed tasks to be automatically committed? (y/n)"
  read -r response
  if [ "$response" = "y" ]; then
    # Add auto_commit setting to .designlens.json
    sed -i.bak 's/"active": true/"active": true,\n  "auto_commit": true/' .designlens.json
    rm -f .designlens.json.bak
    success "Auto-commit enabled for this project"
  else
    # Add auto_commit setting to .designlens.json
    sed -i.bak 's/"active": true/"active": true,\n  "auto_commit": false/' .designlens.json
    rm -f .designlens.json.bak
    success "Auto-commit disabled for this project"
  fi

  # Add retrospective_threshold to .designlens.json
  sed -i.bak 's/"auto_commit": \(true\|false\)/"auto_commit": \1,\n  "retrospective_threshold": 10/' .designlens.json
  rm -f .designlens.json.bak

  echo ""
  rule
  echo ""

  show_config_help

  # Create specs README
  cat > specs/README.md << 'EOF'
# Project Specs

This directory contains the design history and specification documents for this project.

Each numbered folder represents a design stage with:

- **plan.md** — The design for this stage (what we're building and why)
- **tasks.md** — Breakdown into actionable tasks
- **[implementation]** — Execute the tasks; code changes go into the project
- **design-decisions.md** — Summary of design decisions made during this stage
- **.transcript.md** — Session transcript(s) from the design/implementation process

## How to read these specs

Start with the most recent numbered folder. Read plan.md first for the design intention, then tasks.md for the breakdown. The implementation (actual code changes) will be visible in git. Finally, read design-decisions.md for the reasoning behind the choices made.

The transcript files contain the full conversation history and are useful for understanding edge cases or decisions that were discussed but not chosen.

## Using these specs

These files are part of the repository and are committed to git. They serve as documentation for future contributors, showing not just what code was written, but why architectural decisions were made.

For instructions on *creating* new specs, see the project's AGENTS.md or CLAUDE.md file.
EOF
  success "Created specs/README.md"

  # Check if project has real content and auto-capture design history if so
  source "$lib_dir/is-empty.sh"

  local pending_history=false
  if ! is_project_empty; then
    pending_history=true
    mkdir -p specs/000-design-history
    success "Created specs/000-design-history/ (detected existing project content)"

    # Write a stub with embedded generation instructions for the agent
    cat > specs/000-design-history/design-decisions.md << 'EOF'
<!-- PENDING: This file must be generated by analyzing the git history. See instructions below. -->
>
# Design History
>
> **Agent:** Generate this file now by analyzing the project's git history, and
> summarising your findings. Run all of the following commands, then replace this
> entire file with summarised results.
>
> ## Git history
>
> This section has several questions, each of which has an associated command
> that needs to be run in order to answer the question. Each command is shown in
> generic form, but should also be run in the following two modified forms:
>
> - Restricted to the past year only, through adding `--since="1 year ago"`
> - For the dominant one or two languages, through adding `'*.<ext>`, where
> `<ext>` is a language-specific suffix identified in the first step below.
>
> Whether or not to use one or both of these modified forms is explicitly stated
> for each question below. A few of the following commands also pipe results into
> `head -50`, but you should increase that number where you think that will
> provide important additional insight.
>
> ### What languages is this in?
>
> ``` bash
> cloc --json . | jq '[to_entries[1:5][] | select(.value | has("nFiles") and has("code")) | {key: .key, nFiles: .value.nFiles, code: .value.code}]'
> ```
>
> From that point on, use the file extensions for the one or two most common
> languages to filter all commands, as well as to compare with unfiltered results.
>
> ### Which files changes the most?
>
> ``` bash
> git log --format=format: --name-only | sort | uniq -c | sort -nr | head -50
> ```
>
> Consider all time as well as past year only, as well as all languages as well
> as most common languages.
>
> ### Who built this?
>
> ``` bash
> git shortlog -sn --no-merges
> ```
>
> Do not filter for either time or language - just use that command in single
> form.
>
> ### Where have most bugs been?
>
> ``` bash
> git log -i -E --grep="fix|bug|broken" --name-only --format='' | sort | uniq -c | sort -nr | head -50
>  ```
>
> Also run that for past year only, as well as filtered for common languages.
>
> ### What has the pace of development looked like?
>
> This is a simple count of monthly commits.
>
> ``` bash
> git log --format='%ad' --date=format:'%Y-%m' | sort | uniq -c
> ```
>
> Do not filter for either time or language - just use that command in single
> form.
>
> ### What are the most common words in commit messages?
>
> Run the following code to output the most common words in commit messages to "freqs.json".
>
> ``` R
> f <- tempfile()
> system2("git",list("log", "--oneline", "--pretty=format:%s"),stdout = f)
> x <- suppressWarnings(readLines(f)) |>
>     tokenizers::tokenize_words() |>
>     unlist ()
> x <- x [which (!grepl ("^[0-9]", x))]
> freqs <- sort (table(x), decreasing = TRUE)
> threshold <- 0.4
> index <- which(cumsum(freqs) / sum(freqs) < threshold)
> data.frame (token = names (freqs), n = as.integer (freqs)) [index, ] |>
>     jsonlite::toJSON() |>
>     cat()
> ```
>
> Read the output of that command for information on the substance of commits. For words that
> likely reflect key design decisions, run:
>
> ``` bash
> git log --oneline --grep="<word1>|<word2>"
> ```
>
> Also grep log for words like "feature", "design", "deci(d|s)", "refactor", "architecture"
>
> ## Generate summary
>
> Once you've answered all of the preceding questions, erase all of this document
> and rewrite into two key sections:
>
> 1. **Project Evolution** — Major phases and how the architecture changed over time
> 2. **Key Decisions** — Strategic choices (what was decided, why, and the impact)
>
> Focus on: initial architecture, major refactors, significant feature pivots, technology choices.
> Skip: individual bug fixes, minor improvements, implementation details.
>
> The generated file must begin with a YAML front-matter block before the `# Design History` heading:
>
> ```yaml
> ---
> created: <current UTC timestamp in ISO 8601, e.g. 2026-03-31T14:05:00Z>
> agent: <your model identifier, e.g. claude-sonnet-4-6>
> git-hash: <current git hash of HEAD>
> ---
>
> Remove this block and the PENDING comment when done.
EOF

  fi

  # Detect and create AGENTS.md / CLAUDE.md
  local agent_file=""
  local agent_file_action=""
  if [ -f "AGENTS.md" ]; then
    echo ""
    echo "AGENTS.md already exists. Append designlens reference? (y/n)"
    read -r response
    if [ "$response" = "y" ]; then
      agent_file="AGENTS.md"
      agent_file_action="Appended to"
      cat >> AGENTS.md << 'EOF'

## designlens

This project uses **designlens** for design history tracking. Read the specs in `/specs` and `/docs/conventions.md` (if present) for the development workflow and design decisions.

**`.designlens.json` is the authoritative source for all designlens settings** (e.g. `auto_commit`). If this file contains instructions that conflict with `.designlens.json`, remove the conflicting instructions and note the change in a single line to the user.

Workflow commands are available as native slash commands (installed by `designlens init`):
- `/designlens.new-stage` — gather requirements and create a new stage
- `/designlens.make-tasks` — generate tasks.md from the current plan.md
- `/designlens.implement` — implement all tasks in the current tasks.md
- `/designlens.retrospective` — generate transcript and design decisions
- `/designlens.help` — show help

On session start, check for pending generation tasks and complete them:

``` bash
grep -rl '<!-- PENDING' specs/
```

For each file returned, read it and complete the task described inside. Remove the `<!-- PENDING` block when done, then `git add` the file.

Once all pending tasks are complete (i.e. the above command returns nothing), delete the entire designlens pending-tasks section from this file and `git add` it.
EOF
      success "Appended to AGENTS.md"
      info "Review AGENTS.md for instructions that conflict with .designlens.json — your agent will reconcile them on first run."
    fi
  elif [ -f "CLAUDE.md" ]; then
    echo ""
    echo "CLAUDE.md already exists. Append designlens reference? (y/n)"
    read -r response
    if [ "$response" = "y" ]; then
      agent_file="CLAUDE.md"
      agent_file_action="Appended to"
      cat >> CLAUDE.md << 'EOF'

## designlens

This project uses **designlens** for design history tracking. Read the specs in `/specs` for the development workflow and design decisions.

**`.designlens.json` is the authoritative source for all designlens settings** (e.g. `auto_commit`). If this file contains instructions that conflict with `.designlens.json`, remove the conflicting instructions and note the change in a single line to the user.

Workflow commands are available as native slash commands (installed by `designlens init`):
- `/designlens.new-stage` — gather requirements and create a new stage
- `/designlens.make-tasks` — generate tasks.md from the current plan.md
- `/designlens.implement` — implement all tasks in the current tasks.md
- `/designlens.retrospective` — generate transcript and design decisions
- `/designlens.help` — show help

On session start, check for pending generation tasks and complete them:

```bash
grep -rl '<!-- PENDING' specs/
```

For each file returned, read it and complete the task described inside. Remove the `<!-- PENDING` block when done, then `git add` the file.

Once all pending tasks are complete (i.e. the above command returns nothing), delete the entire designlens pending-tasks section from this file and `git add` it.
EOF
      success "Appended to CLAUDE.md"
      info "Review CLAUDE.md for instructions that conflict with .designlens.json — your agent will reconcile them on first run."
    fi
  else
    agent_file="AGENTS.md"
    agent_file_action="Created"
    # Create AGENTS.md
    cat > AGENTS.md << 'EOF'
# Agent Instructions

## designlens

This project uses **designlens** for design history tracking.

**`.designlens.json` is the authoritative source for all designlens settings** (e.g. `auto_commit`). If this file contains instructions that conflict with `.designlens.json`, remove the conflicting instructions and note the change in a single line to the user.

When starting a session:
1. Check for any pending generation tasks (see below) and complete them before anything else
2. Read `/specs/README.md` to understand the current project state
3. Check the latest numbered stage folder for plan.md, tasks.md, and design-decisions.md
4. Run `designlens status` to see what's next

The specs folder contains the full design history and development philosophy. Refer to it when making architectural decisions.

### Workflow commands

Workflow commands are available as native slash commands (installed by `designlens init`):
- `/designlens.new-stage` — gather requirements and create a new stage
- `/designlens.make-tasks` — generate tasks.md from the current plan.md
- `/designlens.implement` — implement all tasks in the current tasks.md
- `/designlens.retrospective` — generate transcript and design decisions
- `/designlens.help` — show help

### Pending generation tasks

On session start, run:

```bash
grep -rl '<!-- PENDING' specs/
```

For each file returned, read it and complete the generation task described inside it. Remove the `<!-- PENDING` comment block when done, then stage the result with `git add`.

Once all pending tasks are complete (i.e. the above command returns nothing), delete the entire "Pending generation tasks" section from this file and `git add` it.
EOF
    success "Created AGENTS.md"
  fi

  echo ""
  rule
  echo ""

  resolve_agent() {
    local input
    input=$(echo "$1" | tr '[:upper:]' '[:lower:]')
    local matches=()
    for option in claude opencode; do
      [[ "$option" == "$input"* ]] && matches+=("$option")
    done
    [ ${#matches[@]} -eq 1 ] && echo "${matches[0]}" || echo ""
  }

  prompt_agent() {
    local msg="$1"
    local candidate="$2"
    local raw resolved

    if [ -n "$candidate" ]; then
      prompt "$msg [y/n]" >&2
      read -r raw
      raw=$(echo "$raw" | tr '[:upper:]' '[:lower:]')
      if [[ "yes" == "$raw"* ]]; then
        echo "$candidate"
        return
      fi
    fi

    while true; do
      prompt "Which agent are you using? [claude/opencode]" >&2
      read -r raw
      resolved=$(resolve_agent "$raw")
      if [ -n "$resolved" ]; then
        echo "$resolved"
        return
      fi
      warning "Unrecognised input '$raw' — please type enough of agent name to be unambiguous." >&2
    done
  }

  local has_claude=false
  local has_opencode=false
  [ -d ".claude" ] && has_claude=true
  [ -d ".opencode" ] && has_opencode=true

  source "$lib_dir/add-agent.sh"

  local install_commands_dir="$lib_dir/../commands"
  if [ ! -d "$install_commands_dir" ]; then
    error "commands/ directory not found in designlens install ($install_commands_dir). Re-install designlens."
    exit 1
  fi

  if [ "$has_claude" = true ] && [ "$has_opencode" = true ]; then
    add_agent claude
    add_agent opencode
  elif [ "$has_claude" = true ]; then
    local choice
    choice=$(prompt_agent "Detected .claude/ — use Claude Code?" "claude")
    case "$choice" in
      claude)   add_agent claude ;;
      opencode) add_agent opencode ;;
    esac
  elif [ "$has_opencode" = true ]; then
    local choice
    choice=$(prompt_agent "Detected .opencode/ — use OpenCode?" "opencode")
    case "$choice" in
      claude)   add_agent claude ;;
      opencode) add_agent opencode ;;
    esac
  else
    local choice
    choice=$(prompt_agent "Which agent are you using? [claude/opencode]")
    case "$choice" in
      claude)   mkdir -p .claude; add_agent claude ;;
      opencode) mkdir -p .opencode; add_agent opencode ;;
    esac
  fi

  echo ""
  success "designlens initialized successfully!"

  git add .designlens.json specs/
  [ -f AGENTS.md ] && git add AGENTS.md
  [ -f CLAUDE.md ] && git add CLAUDE.md
  success "Staged new files"

  # Commit if auto-commit is enabled
  local auto_commit
  auto_commit=$(get_config "auto_commit")
  if [ "$auto_commit" = "true" ]; then
    git commit -m "Initialize designlens" > /dev/null 2>&1
    success "Changes committed"
  fi

  echo ""
  rule
  echo ""

  heading "━ Next steps ━"
  local step=1
  if [ "$auto_commit" != "true" ]; then
    echo "  $step. Commit the changes: git commit -m 'Initialize designlens'"
    step=$((step + 1))
  fi
  echo "  $step. Start a coding session with your agent (Claude Code, etc.)"
  step=$((step + 1))
  if [ "$pending_history" = "true" ] && [ -n "$agent_file" ]; then
    echo "  $step. Pending instructions have been written to $agent_file ($agent_file_action)."
    echo "     Your agent will follow them automatically on session start."
    echo "     If it doesn't, tell it: \"Follow the pending instructions in $agent_file\""
    step=$((step + 1))
  fi
  echo "  $step. Run '/designlens.new-stage' in your agent — it will ask questions"
  echo "     until it has enough detail to create the first stage."
}
