#!/bin/bash

# Initialize a project to use designlens
# Creates /specs folder, lockfile, and AGENTS.md pointer

spec_init() {
  # Source helpers
  local lib_dir
  lib_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
  source "$lib_dir/colors.sh"
  source "$lib_dir/config.sh"
  source "$lib_dir/logo.sh"

  show_logo

  if [ ! -d .git ]; then
    echo "Initializing git repository..."
    git init
    success "Git repository initialized"
  fi

  if [ -d specs ]; then
    error "/specs folder already exists. Project is already initialized."
    exit 1
  fi

  echo "Initializing designlens project..."

  # Create /specs directory
  mkdir -p specs
  success "Created /specs directory"

  # Read metadata from installed tool
  METADATA_FILE="$lib_dir/../designlens.json"
  if [ -f "$METADATA_FILE" ]; then
    TOOL_VERSION=$(grep -o '"Version": *"[^"]*"' "$METADATA_FILE" | cut -d'"' -f4)
    TOOL_URL=$(grep -o '"URL": *"[^"]*"' "$METADATA_FILE" | cut -d'"' -f4)
  else
    TOOL_VERSION="unknown"
    TOOL_URL="https://github.com/ropensci/designlens"
  fi

  # Create project config file (metadata + local settings)
  cat > .designlens.json << EOF
{
  "tool": "designlens",
  "version": "$TOOL_VERSION",
  "docs": "$TOOL_URL/blob/main/docs/conventions.md",
  "active": true
}
EOF
  success "Created .designlens.json"

  echo ""
  rule
  echo ""

  # Ask about auto-commit preference (only on first init for this project)
  echo ""
  prompt "Would you like completed tasks to be automatically committed? (y/n)"
  read -r response
  if [ "$response" = "y" ]; then
    # Add auto_commit setting to .designlens.json
    sed -i.bak 's/"active": true/"active": true,\n  "auto_commit": true/' .designlens.json
    rm -f .designlens.json.bak
    success "Auto-commit enabled for this project"
  else
    # Add auto_commit setting to .designlens.json
    sed -i.bak 's/"active": true/"active": true,\n  "auto_commit": false/' .designlens.json
    rm -f .designlens.json.bak
    success "Auto-commit disabled for this project"
  fi

  echo ""
  rule
  echo ""

  show_config_help

  # Create specs README
  cat > specs/README.md << 'EOF'
# Project Specs

This directory contains the design history and specification documents for this project.

Each numbered folder represents a design stage with:

- **plan.md** — The design for this stage (what we're building and why)
- **tasks.md** — Breakdown into actionable tasks
- **[implementation]** — Execute the tasks; code changes go into the project
- **design-decisions.md** — Summary of design decisions made during this stage
- **.transcript.md** — Session transcript(s) from the design/implementation process

## How to read these specs

Start with the most recent numbered folder. Read plan.md first for the design intention, then tasks.md for the breakdown. The implementation (actual code changes) will be visible in git. Finally, read design-decisions.md for the reasoning behind the choices made.

The transcript files contain the full conversation history and are useful for understanding edge cases or decisions that were discussed but not chosen.

## Using these specs

These files are part of the repository and are committed to git. They serve as documentation for future contributors, showing not just what code was written, but why architectural decisions were made.

For instructions on *creating* new specs, see the project's AGENTS.md or CLAUDE.md file.
EOF
  success "Created specs/README.md"

  # Check for extensive git history and auto-capture if present
  COMMIT_COUNT=$(git rev-list --count HEAD 2>/dev/null || echo 0)
  HISTORY_THRESHOLD=50

  local pending_history=false
  if [ "$COMMIT_COUNT" -gt "$HISTORY_THRESHOLD" ]; then
    pending_history=true
    mkdir -p specs/000-design-history
    success "Created specs/000-design-history/ (detected $COMMIT_COUNT commits)"

    # Write a stub with embedded generation instructions for the agent
    cat > specs/000-design-history/design-decisions.md << 'EOF'
<!-- PENDING: This file must be generated by analyzing the git history. See instructions below. -->

# Design History

> **Agent:** Generate this file now by analyzing the project's git history.
> Run the following, examine key commits, then replace this entire file with the result.
>
> ```bash
> git log --oneline --all | head -100
> git log --all --oneline --stat | head -100
> git log --all --oneline --since="1 year ago"
> git log --all --oneline --grep="feature\|design\|architecture\|refactor"
> ```
>
> Document (~300-500 words):
> 1. **Project Evolution** — Major phases and how the architecture changed over time
> 2. **Key Decisions** — Strategic choices (what was decided, why, and the impact)
>
> Focus on: initial architecture, major refactors, significant feature pivots, technology choices.
> Skip: individual bug fixes, minor improvements, implementation details.
> Remove this block and the PENDING comment when done.
EOF

  fi

  # Detect and create AGENTS.md / CLAUDE.md
  local agent_file=""
  local agent_file_action=""
  if [ -f "AGENTS.md" ]; then
    echo ""
    echo "AGENTS.md already exists. Append designlens reference? (y/n)"
    read -r response
    if [ "$response" = "y" ]; then
      agent_file="AGENTS.md"
      agent_file_action="Appended to"
      cat >> AGENTS.md << 'EOF'

## designlens

This project uses **designlens** for design history tracking. Read the specs in `/specs` and `/docs/conventions.md` (if present) for the development workflow and design decisions.

On session start, check for pending generation tasks and complete them:

```bash
grep -rl '<!-- PENDING' specs/
```

For each file returned, read it and complete the task described inside. Remove the `<!-- PENDING` block when done, then `git add` the file.

Once all pending tasks are complete (i.e. the above command returns nothing), delete the entire designlens pending-tasks section from this file and `git add` it.
EOF
      success "Appended to AGENTS.md"
    fi
  elif [ -f "CLAUDE.md" ]; then
    echo ""
    echo "CLAUDE.md already exists. Append designlens reference? (y/n)"
    read -r response
    if [ "$response" = "y" ]; then
      agent_file="CLAUDE.md"
      agent_file_action="Appended to"
      cat >> CLAUDE.md << 'EOF'

## designlens

This project uses **designlens** for design history tracking. Read the specs in `/specs` for the development workflow and design decisions.

On session start, check for pending generation tasks and complete them:

```bash
grep -rl '<!-- PENDING' specs/
```

For each file returned, read it and complete the task described inside. Remove the `<!-- PENDING` block when done, then `git add` the file.

Once all pending tasks are complete (i.e. the above command returns nothing), delete the entire designlens pending-tasks section from this file and `git add` it.
EOF
      success "Appended to CLAUDE.md"
    fi
  else
    agent_file="AGENTS.md"
    agent_file_action="Created"
    # Create AGENTS.md
    cat > AGENTS.md << 'EOF'
# Agent Instructions

## designlens

This project uses **designlens** for design history tracking.

When starting a session:
1. Check for any pending generation tasks (see below) and complete them before anything else
2. Read `/specs/README.md` to understand the current project state
3. Check the latest numbered stage folder for plan.md, tasks.md, and design-decisions.md
4. Run `designlens status` to see what's next
5. Follow the guidance in `/docs/conventions.md` for the workflow

The specs folder contains the full design history and development philosophy. Refer to it when making architectural decisions.

### Starting a new stage

The user describes what they want to build. **Do not call `designlens new-stage` until you have enough information to write a concrete, actionable plan.** If the description is vague, missing scope, or lacks clear goals, ask clarifying questions before proceeding.

Once you have sufficient detail:
1. Derive a short verb-noun name from the description (e.g. `add-auth`, `refactor-parser`, `migrate-storage`) — do not ask the user for this
2. Call: `designlens new-stage "<name>" "<full description>"`
3. Then flesh out the generated plan.md and tasks.md with the full design

### Pending generation tasks

On session start, run:

```bash
grep -rl '<!-- PENDING' specs/
```

For each file returned, read it and complete the generation task described inside it. Remove the `<!-- PENDING` comment block when done, then stage the result with `git add`.

Once all pending tasks are complete (i.e. the above command returns nothing), delete the entire "Pending generation tasks" section from this file and `git add` it.
EOF
    success "Created AGENTS.md"
  fi

  echo ""
  success "designlens initialized successfully!"

  # Stage all newly-created files
  git add .designlens.json specs/
  [ -f AGENTS.md ] && git add AGENTS.md
  [ -f CLAUDE.md ] && git add CLAUDE.md
  success "Staged new files"

  # Commit if auto-commit is enabled
  local auto_commit=$(get_config "auto_commit")
  if [ "$auto_commit" = "true" ]; then
    git commit -m "Initialize designlens" > /dev/null 2>&1
    success "Changes committed"
  fi

  echo ""
  rule
  echo ""

  heading "━ Next steps ━"
  local step=1
  if [ "$auto_commit" != "true" ]; then
    echo "  $step. Commit the changes: git commit -m 'Initialize designlens'"
    step=$((step + 1))
  fi
  echo "  $step. Start a coding session with your agent (Claude Code, etc.)"
  step=$((step + 1))
  if [ "$pending_history" = "true" ] && [ -n "$agent_file" ]; then
    echo "  $step. Pending instructions have been written to $agent_file ($agent_file_action)."
    echo "     Your agent will follow them automatically on session start."
    echo "     If it doesn't, tell it: \"Follow the pending instructions in $agent_file\""
    step=$((step + 1))
  fi
  echo "  $step. Tell your agent what you want to build — it will ask clarifying questions,"
  step=$((step + 1))
  echo "     generate a name, and call 'designlens new-stage' when it has enough detail."
}
