#!/bin/bash

# Helper for creating semi-anonymized session transcripts
# Speaker attribution uses git user.name; message content is anonymized

# Source colors and logo
lib_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source "$lib_dir/colors.sh"
source "$lib_dir/logo.sh"

spec_transcript() {
  local input_file="$1"

  local git_user
  git_user=$(git config user.name 2>/dev/null || echo "unknown")

  if [ ! -f "$input_file" ]; then
    # CREATE MODE: instruct agent to create the transcript from scratch
    heading "============================================"
    echo ""
    echo "## SUB-TASK: Create session transcript"
    echo ""
    echo "Create a semi-anonymized summary transcript of this design session."
    echo "Save it to: $input_file"
    echo ""
    echo "### Format:"
    echo ""
    echo "# Session Transcript: [Stage Title]"
    echo ""
    echo "## Session Overview"
    echo "[1-2 sentences summarizing what was discussed and decided]"
    echo ""
    echo "## Design Decisions Made"
    echo ""
    echo "### Decision 1: [What was decided]"
    echo "**Chosen:** [The option selected]"
    echo "**Rationale:** [Why this was chosen over alternatives]"
    echo "**Tradeoffs:** [What was sacrificed or deferred]"
    echo "**Proposed by:** [$git_user | agent | joint]"
    echo ""
    echo "### Decision 2: [What was decided]"
    echo "[Same structure]"
    echo ""
    echo "## Tradeoffs Considered"
    echo "- [Option A vs Option B]: [Why the chosen option won]"
    echo ""
    echo "## Open Questions"
    echo "- [Any unresolved questions or deferred items]"
    echo ""
    echo "### ANONYMIZATION REQUIREMENTS (non-negotiable):"
    echo "- Speaker labels: use git user.name ($git_user), not 'human', 'user', or real names"
    echo "- NO personal expressions, anecdotes, or preferences in first person"
    echo "- NO email addresses or identifying information"
    echo "- NO user counts, revenue, or business-specific details"
    echo "- Focus on technical reasoning and decisions, not speakers"
    echo ""
    echo "### ROLE ATTRIBUTION (required for every decision):"
    echo "- Every decision MUST have a 'Proposed by' field"
    echo "- Use git user.name ($git_user) for the human participant (preferred)"
    echo "- Use 'human' only if git user.name is unavailable"
    echo "- Use 'agent' for the AI assistant"
    echo "- Use 'joint' when both contributed equally"
    echo ""
    echo "### Self-contained requirement:"
    echo "Transcripts must be fully self-contained. Do not reference external documents"
    echo "without also summarizing the relevant content inline. If context from a plan,"
    echo "prior design decision, or other doc shaped the decisions in this session,"
    echo "include a brief, de-personalized summary of that context within the transcript."
    echo "Readers should not need to open other files to understand the decisions recorded here."
    echo ""
    echo "### Length: 150–400 words. Concise and scannable."
    echo ""
    heading "============================================"
    return
  fi

  heading "Transcript semi-anonymization review"
  echo ""
  info "Note: designlens transcripts are SUMMARIES of design decisions, not raw conversation."
  info "They must be semi-anonymized before being committed to a project repo:"
  echo ""
  echo "  Speaker labels : use git user.name ($git_user)"
  echo "  Message content: anonymized — remove personal expressions and identifying info"
  echo ""
  heading "Checklist:"
  echo "  ☐ Every decision has a 'Proposed by' field (git user.name, 'agent', or 'joint')"
  echo "  ☐ Speaker labels use git user.name (not 'human' or 'user')"
  echo "  ☐ No personal expressions or anecdotes in message content"
  echo "  ☐ No email addresses or identifiers in message content"
  echo "  ☐ No personal preferences stated in first person"
  echo "  ☐ No user counts, revenue, or business-specific details that identify the company"
  echo "  ☐ Focuses on technical reasoning and decisions, not personal opinions"
  echo "  ☐ Follows the structured format (Session Overview, Decisions, Tradeoffs, etc.)"
  echo ""
  prompt "Edit the file manually to remove any identifying information from message content:"
  echo "  $input_file"
  echo ""
  prompt "Verify compliance with:"
  echo "  grep -E '(email|@|facebook|twitter|slack|company|revenue|users?)' $input_file"
}
